### ISSUE TITLE
No data set found.

### ISSUE THREAD

**Issue by vishalvashistha87** [engineeringterminal/antenna-pattern-plotting#1]
Can you please upload the data set used by you ? I try to run this code on my data set, but it shows some error. 
This line was giving me error. 
pattern_db = np.reshape(raw_data[:,3], (len(phi), len(theta), len(freq)), order='F')
[main.txt](https://github.com/engineeringterminal/antenna-pattern-plotting/files/2035547/main.txt)

**Comment by nalyd88** [comment]
Good idea. I'll get the example dataset uploaded soon.

**Comment by vishalvashistha87** [comment]
Perhaps, you can tell how can I used this data to use your code. In general most simulator provides the data in similar format. I tried your code but this ends up with error in pattern_dB line. 

[my_far_field.txt](https://github.com/engineeringterminal/antenna-pattern-plotting/files/2044439/my_far_field.txt)

**Comment by nalyd88** [comment]
You just need to customize the code that reads the data to fit your particular file format. In my example data there is a frequency column while your data just has theta and phi. Also, the pattern info my not be the 3rd column as in my example. Basically you just need to get pattern_db that you want to plot to be an nxm matrix where n is the number of phi samples and m is the number of theta samples. Then you can just put that into the plotting code.

    # my code
    pattern_db[:,:,fidx]  # grabbing the slice for a specific frequency

    # after you change your code to read in your file
    pattern_db # in your case pattern_bd should already be the right size

**Comment by vishalvashistha87** [comment]
hi, thanks for your reply. 
I am not getting why you are using this np.reshape function. My data is already column separated data, where first column is thetha, second is phi and third column is abs directivity.  Are you trying to make some meshgrid ? 
Actually, for me this command (pattern_db = np.reshape(dir_dB, (len(phi), len(theta)), order='F'))  is giving me value error (ValueError: cannot reshape array of size 2664 into shape (2664,2664)).   
[main.txt](https://github.com/engineeringterminal/antenna-pattern-plotting/files/2062694/main.txt)


See my code clean for this data. 

`# Clean up the data. 
import csv
import numpy as np
with open('main.txt', newline='') as f:
    reader = csv.reader(f)
    header_line_1 = next(reader)
    header_line_2 = next(reader)
    data = [row[0].split() for row in reader]
    data = np.array(data,dtype=np.float)

theta = data[:,0]     # theta values are in degree with a interval of 5 degree. 
phi = data[:,1]       # phi values are in degree with a interval of 5 degree. 
dir_dB = data[:,2]    # Abs values of directivity on dBi scale.

pattern_db = np.reshape(dir_dB, (len(phi), len(theta)), order='F') `

**Comment by vishalvashistha87** [comment]
I would also like to see your data format for future reference purpose.

**Comment by nalyd88** [comment]
You are getting close. The theta and phi vectors in your text file have duplicate entries. Thats why my code has the call to `unique`. Your theta and phi vectors are actually much smaller that 2664 values. Thats why I reshape the data so its a 2D grid that corresponds to the unique values of theta and phi (37 values and 72 values respectively at 5 degree step sizes).  So your data needs to be resphaped to be a 37 by 72 element matrix. 

Change 

    theta = data[:,0] # theta values are in degree with a interval of 5 degree.
    phi = data[:,1] # phi values are in degree with a interval of 5 degree.

to 

    theta = np.unique(data[:,0]) # theta values are in degree with a interval of 5 degree.
    phi = np.unique(data[:,1]) # phi values are in degree with a interval of 5 degree.

so that `len(phi)` is 72 and `len(theta)` is 37 and I think it will work. Also, the order of the reshape needs to correspond to how the data is organized in the file. In your file, `theta` is changing fastest so I think you need `np.reshape(dir_dB, (len(theta), len(phi)), order='F')`.

**Comment by vishalvashistha87** [comment]
I am sorry, but I still have doubt that we are on same page. Let me explain you about data.  The simulator is giving me a mesh grid of data between theta, phi and directivity. This mean, first theta is varied from 0 to 180 with step size of 05 degree and phi is constant to 0 degree and calculate the directivity. The same is followed for phi from 0 to 360 with step size of 05 degree. **So basically simulator is itself giving me a meshgrid between theta(first colum), phi(second column), and dir(third colum)**. Now, in general, I can simply plot a 3D data from this code. 
`theta, phi = np.meshgrid(theta, phi)
fig = plt.figure()
ax = plt.axes(projection='3d')
ax.contour3D(theta, phi, dir_dB, 50, cmap='binary')`   

# perhaps the better visualization, I would like to use your code using mlab library. 

Now, let's come to main problem, the data is in cylindrical coordinate system, so I am not getting how to plot cylindrical coordinate data into cartesian coordinate system.  Perhaps we need to change it.
You are using something like this to calculate r (the only things which is perhaps not clear for me). 

```
## Plot in 3D ##

r = pattern_db[:,:,fidx] - pltmin
r[r < 0.0] = 0.0
```
Now, I am not getting how can you set pltmin with fixed value. I think you should check the minima of dir_dB data and than you can scale this data. Second things, dir_dB data is in dBi scale, so I suppose it must be converted back to normal scale before using it to convert from spherical to cartesian coordinate system.

**Comment by vishalvashistha87** [comment]
What you suggested, that I try and getting error in this line. 

`plt.pcolor(phi2d, theta2d, pattern_db[:,:],
    vmin=pltmin, vmax=pltmax, cmap="jet")`


Here is full updated code. I will be happy if you can update my code. 

```
# Clean up the data. 
import csv
import numpy as np
with open('main.txt', newline='') as f:
    reader = csv.reader(f)
    header_line_1 = next(reader)
    header_line_2 = next(reader)
    data = [row[0].split() for row in reader]
    data = np.array(data,dtype=np.float)

theta = np.unique(data[:,0])     # theta values are in degree with a interval of 5 degree. 
phi = np.unique(data[:,1])       # phi values are in degree with a interval of 5 degree. 
dir_dB = data[:,2]    # Abs values of directivity on dBi scale.

pattern_db = np.reshape(dir_dB, (len(theta), len(phi)), order='F')

## Plot in 2D ##

# Index of frequency to plot
fidx = 1

# Control plot dynamic range
pltmax = 5
pltmin = -35

# Create the 2D colormap
plt.figure()
theta2d, phi2d = np.meshgrid(theta, phi)
plt.pcolor(phi2d, theta2d, pattern_db[:,:],
    vmin=pltmin, vmax=pltmax, cmap="jet")
plt.xlabel("Phi [degrees]")
plt.ylabel("Theta [degrees]")
plt.colorbar(label="Realized Gain [dBi]")
# plt.show()
# Clean up the data. 
import csv
import numpy as np
with open('main.txt', newline='') as f:
    reader = csv.reader(f)
    header_line_1 = next(reader)
    header_line_2 = next(reader)
    data = [row[0].split() for row in reader]
    data = np.array(data,dtype=np.float)

theta = np.unique(data[:,0])     # theta values are in degree with a interval of 5 degree. 
phi = np.unique(data[:,1])       # phi values are in degree with a interval of 5 degree. 
dir_dB = data[:,2]    # Abs values of directivity on dBi scale.

pattern_db = np.reshape(dir_dB, (len(theta), len(phi)), order='F')

## Plot in 2D ##

# Index of frequency to plot
fidx = 1

# Control plot dynamic range
pltmax = 5
pltmin = -35

# Create the 2D colormap
plt.figure()
theta2d, phi2d = np.meshgrid(theta, phi)
plt.pcolor(phi2d, theta2d, pattern_db[:,:],
    vmin=pltmin, vmax=pltmax, cmap="jet")
plt.xlabel("Phi [degrees]")
plt.ylabel("Theta [degrees]")
plt.colorbar(label="Realized Gain [dBi]")
# plt.show()

```

**Comment by nalyd88** [comment]
Hello,

Sorry I do not have time to rewrite your code for you. But if you need help and would like to hire us to develop some code for you contact us through the engineeringterminal.com website.

To answer your above two questions:
1. You can scale the plot however you like. I like having a fixed value because often I don't need to see a -100 dB null when most of the pattern is between +20 and -20 dB for example.
2. The conversion to cartesian is just for drawing purposes. Since you want to plot dB you do not need to convert to linear prior to converting from spherical to cartesian coordinates. Please see the example plots in the tutorial. http://engineeringterminal.com/electrical-engineering/tutorials/plotting-antenna-patterns.html 

Also, since the original issue was resolved I am locking this issue. Please feel free to contact us through the ET website!

Thanks!
